### ISSUE TITLE
Item Descriptions

### ISSUE THREAD

**Issue by Pralunko** [elementGEMO/SeekingItemReworks#3]
The mod still has the item descriptions of the original versions of the items instead of the new ones (for example knockback fin still says it just knocks enemies up and doesn't say that it also deals more damage to enemies that are airborne).
Don't know if I'm doing something wrong or if it's a feature that will be included in a future version (or maybe it's simply not planned).

**Comment by elementGEMO** [comment]
There's a good chance that you're running a mod that overrides the description of the rework, like Unified Item Descriptions or something similar.

**Comment by Pralunko** [comment]
Damn, you are right, thought I had done all the testing, but apparently not, thanks for the help though, I really like your item ideas and now that the descriptions work it's even better
